### PR TITLE
Breaking up Game#makeMove logic

### PR DESCRIPTION
**Pull request by tsukiy0**
* flatten if/else block

### CODE REVIEW

**Comment by tsukiy0** [comment]
still looking up whether I can store the if/else within Game#processMarkerPlacement in a collection. e.g. Map<Condition,Lamda>

**Comment by mwpeng** [comment]
I will look into it how to do refactoring of the conditions.

**Comment by mwpeng** [comment]
#4

**Comment by tsukiy0** [comment]
Handled in #4

**Pull request closed without merging**
